---
name: 'Manual Build'
on: 
  workflow_dispatch:
jobs:
  archlinux:
    name: yt-dlp:archlinux container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfiles/yt-dlp
          tags: ghcr.io/gunanr/yt-dlp:archlinux
          push: true
  debian12:
    name: yt-dlp:debian12 container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfiles/yt-dlp
          tags: ghcr.io/gunanr/yt-dlp:debian12
          push: true
